cake-contrib/CakeContrib.Guidelines

GitReleaseManager.yaml
src/CakeContrib.Guidelines.nuspec

updated footer in GitReleaseManager.yaml and description in nuspec

---

README.md

(GH-3) corrected reference to appveyor

---

README.md
src/build/CakeContrib.Guidelines.targets
src/build/CakeReference.targets
src/build/Icon.targets

Check Cake.Core and Cake.Common for PrivateAssets

---

CODE_OF_CONDUCT.md
README.md

(GH-11) Updated README and CODE_OF_CONDUCT

---

README.md
src/CakeContrib.Guidelines.nuspec

updated the short description in README and nuspec

---

.github/workflows/publishDocs.yml
README.md
config.wyam
docs/input/guidelines/CakeContribIcon.md
docs/input/guidelines/PrivateAssets.md
docs/input/guidelines/index.cshtml
docs/input/index.cshtml
docs/input/rules/ccg0001.md
docs/input/rules/ccg0002.md
docs/input/rules/ccg0003.md
docs/input/rules/ccg0004.md
docs/input/rules/index.cshtml
recipe.cake

moved documentation from README into wyam-generated docs.

---

.github/workflows/updateToc.yml
CODE_OF_CONDUCT.md
CONTRIBUTING.md
README.md
docs/input/guidelines/CakeContribIcon.md
docs/input/guidelines/PrivateAssets.md
docs/input/rules/ccg0001.md
docs/input/rules/ccg0002.md
docs/input/rules/ccg0003.md
docs/input/rules/ccg0004.md

(GH-20) add new action: update TOC so TOCs are updated automatically.

---

recipe.cake

to *not* say "... the CakeContrib.Guidelines addin ..." but rather simply
"... CakeContrib.Guidelines ..."

(GH-54) updated gitter/twitter-message

---

.gitignore
README.md

(GH-70) added a link to GitHub discussions

---

docs/input/rules/ccg0005.md
docs/input/rules/ccg0007.md

also, fixed one broken link
fixes #75

(GH-75) corrected the "fix" for CCG0007

---

.github/workflows/build.yml

(GH-111) updated gh-actions to best practices

---

GitReleaseManager.yaml

(GH-110) updated GRM config

---

docs/input/guidelines/RecommendedReferences.md
docs/input/guidelines/TargetFramework.md
src/Guidelines/build/RequiredFiles.targets
src/Guidelines/build/RequiredReferences.targets
src/Tasks.Tests/CalculateProjectTypeTests.cs
src/Tasks.Tests/Fixtures/RequiredFileEditorconfigFixture.cs
src/Tasks.Tests/Fixtures/RequiredFileStylecopJsonFixture.cs
src/Tasks.Tests/Fixtures/RequiredReferencesFixture.cs
src/Tasks.Tests/Fixtures/TargetFrameworkVersionsFixture.cs
src/Tasks.Tests/RequiredFileEditorconfigTests.cs
src/Tasks.Tests/RequiredFilesStylecopJsonTests.cs
src/Tasks.Tests/RequiredReferencesTests.cs
src/Tasks.Tests/TargetFrameworkVersionsTests.cs
src/Tasks/CalculateProjectType.cs
src/Tasks/RequiredFileEditorconfig.cs
src/Tasks/RequiredFileStylecopJson.cs
src/Tasks/RequiredReferences.cs
src/Tasks/TargetFrameworkVersions.cs

Rules skipped for recipes:
CCG0005, CCG0006, CCG0007
fixes: #112

(GH-112) added ProjectType: Recipe

---

docs/input/guidelines/CakeContribIcon.md
docs/input/guidelines/PrivateAssets.md
docs/input/guidelines/RecommendedReferences.md
docs/input/guidelines/RecommendedTags.md
docs/input/guidelines/TargetFramework.md
docs/input/rules/ccg0008.md
docs/input/settings/fragments/OmitRecommendedTag.md
docs/input/settings/index.md
src/Guidelines/build/CakeContrib.Guidelines.targets
src/Guidelines/build/RecommendedTags.targets
src/Tasks.IntegrationTests/E2eTests.cs
src/Tasks.IntegrationTests/Fixtures/E2eTestFixture.cs
src/Tasks.Tests/Fixtures/RequiredTagsFixture.cs
src/Tasks.Tests/RecommendedTagsTests.cs
src/Tasks/RecommendedTags.cs

(GH-100) added recommended tags

---

.github/workflows/updateToc.yml

from remote repositories
fixes #118

(GH-118) do not run updateToc on PRs

---

docs/input/guidelines/RecommendedCakeVersion.md
docs/input/rules/ccg0009.md
docs/input/settings/fragments/OmitRecommendedCakeVersion.md
docs/input/settings/index.md
src/Guidelines/build/CakeContrib.Guidelines.targets
src/Guidelines/build/RecommendedCakeVersion.targets
src/Tasks.IntegrationTests/E2eTests.cs
src/Tasks.Tests/Extensions/StringExtensionTests.cs
src/Tasks.Tests/Fixtures/BaseBuildFixture.cs
src/Tasks.Tests/Fixtures/RecommendedCakeVersionFixture.cs
src/Tasks.Tests/RecommendedCakeVersionTests.cs
src/Tasks.Tests/RecommendedTagsTests.cs
src/Tasks/CalculateProjectType.cs
src/Tasks/RecommendedCakeVersion.cs
src/Tasks/Testability/FileSearcher.cs
src/Tasks/Testability/IFileFacade.cs

(GH-98) implemented a check for a recommended Cake version.

---

.github/workflows/updateToc.yml
docs/input/settings/index.md

(GH-122) set toc-generator to always create PRs

---

docs/input/guidelines/RecommendedTags.md
docs/input/rules/ccg0008.md
src/Tasks.IntegrationTests/E2eTests.cs
src/Tasks.IntegrationTests/Fixtures/E2eTestFixture.cs
src/Tasks.Tests/Fixtures/RequiredTagsFixture.cs
src/Tasks.Tests/RecommendedTagsTests.cs
src/Tasks/RecommendedTags.cs

(GH-127) added a warning when tags contain comma

---

.github/workflows/codeql-analysis.yml
.github/workflows/publishDocs.yml

(GH-131) fixed codeql-analysis

---

src/Tasks.Tests/CalculateProjectTypeTests.cs
src/Tasks/CalculateProjectType.cs

(GH-139) fixed detection of Recipe ProjectType

---

docs/input/_Bottom.cshtml
docs/input/assets/css/override.less
src/Guidelines/Guidelines.csproj

also, fixed the `IsPackagable` error
fixes #109

(GH-109) replaced the gitter link with discussions

---

src/Guidelines/Guidelines.csproj

Fixes #158 
I added the needed settings in the project file

Settings for readme in nupkg

---

src/Guidelines/build/RecommendedCakeVersion.targets
src/Tasks.IntegrationTests/E2eTests.cs
src/Tasks.IntegrationTests/Fixtures/E2eTestFixture.cs
src/Tasks.Tests/Fixtures/TargetFrameworkVersionsFixture.cs
src/Tasks.Tests/TargetFrameworkVersionsTests.cs
src/Tasks/TargetFrameworkVersions.cs

(#170) update recommendations for Cake 2.0.0

---

.github/workflows/build.yml
.github/workflows/codeql-analysis.yml

(#241) bunped GitHub worker machines

---

docs/input/guidelines/CakeInternalReferences.md
docs/input/rules/ccg0010.md
src/CakeContrib.Guidelines.sln
src/Generators/Commands/PackageReferencesCommand.cs
src/Generators/Generators.csproj
src/Generators/Program.cs
src/Guidelines/build/CakeContrib.Guidelines.targets
src/Guidelines/build/CakeInternalReferences.targets
src/Tasks.Tests/CheckCakeInternalReferencesTests.cs
src/Tasks.Tests/Fixtures/CheckCakeInternalReferencesFixture.cs
src/Tasks/CakeVersions.cs
src/Tasks/CheckCakeInternalReferences.cs
src/Tasks/TargetFrameworkVersions.cs

To warn if an addin/module references a package that is already provided by Cake.
fixes #296

(#296)  implemented CCG0010

---

docs/input/guidelines/CakeContribIcon.md
docs/input/guidelines/PrivateAssets.md
docs/input/guidelines/RecommendedCakeVersion.md
docs/input/guidelines/RecommendedReferences.md
docs/input/guidelines/RecommendedTags.md
docs/input/guidelines/TargetFramework.md
docs/input/guidelines/examples/Editorconfig.md
docs/input/guidelines/examples/StyleCopJson.md
docs/input/rules/ccg0001.md
docs/input/rules/ccg0002.md
docs/input/rules/ccg0003.md
docs/input/rules/ccg0004.md
docs/input/rules/ccg0005.md
docs/input/rules/ccg0006.md
docs/input/rules/ccg0007.md
docs/input/rules/ccg0008.md
docs/input/rules/ccg0009.md
docs/input/settings/fragments/IconOmitImport.md
docs/input/settings/fragments/OmitPrivateCheck.md
docs/input/settings/fragments/OmitRecommendedCakeVersion.md
docs/input/settings/fragments/OmitRecommendedReference.md
docs/input/settings/fragments/OmitRecommendedTag.md
docs/input/settings/fragments/OmitTargetFramework.md
docs/input/settings/fragments/OverrideCakeVersion.md
docs/input/settings/index.md
src/Tasks/RecommendedCakeVersion.cs

(#225) added documentation of CakeContribGuidelinesOverrideTargetFrameworkCakeVersion

---

README.md

(#223) fix build-badge

---

docs/input/guidelines/TargetFramework.md
src/Tasks.IntegrationTests/E2eTests.cs
src/Tasks.Tests/Extensions/VersionExtensionTests.cs
src/Tasks.Tests/TargetFrameworkVersionIgnoreCaseComparerTests.cs
src/Tasks.Tests/TargetFrameworkVersionsTests.cs
src/Tasks/TargetFrameworkVersions.cs

(#220) raise CCG0007 on multi-targeting modules

---

docs/input/guidelines/CakeInternalReferences.md
docs/input/guidelines/TargetFramework.md
src/Tasks.Tests/CheckCakeInternalReferencesTests.cs
src/Tasks.Tests/TargetFrameworkVersionsTests.cs
src/Tasks/CakeVersions.cs
src/Tasks/CheckCakeInternalReferences.cs
src/Tasks/TargetFrameworkVersions.cs

(#290) Update Guidelines to include Cake 4.0.0

---

src/Guidelines/build/RecommendedCakeVersion.targets

(#295) bump RecommendedCakeVersion to 4.0.0

---

recipe.cake

(#326) disable codecov

---

docs/input/index.cshtml

fix for Discussion #4333 (PR as req by Pascal Berger)

---

docs/input/guidelines/CakeInternalReferences.md
docs/input/guidelines/TargetFramework.md
src/Generators/Commands/PackageReferencesCommand.cs
src/Tasks.Tests/CheckCakeInternalReferencesTests.cs
src/Tasks.Tests/TargetFrameworkVersionsTests.cs
src/Tasks/CakeVersions.cs
src/Tasks/CheckCakeInternalReferences.cs
src/Tasks/TargetFrameworkVersions.cs

(#365) Update Guidelines to include Cake 5.0.0

---

src/Guidelines/build/RecommendedCakeVersion.targets

(#372) update recommended cake version to 5.0.0
